#!/usr/bin/env python3
"""
Integrate content previews into timeline by-year pages.

Loads content previews from batch JSON files and updates all year-based timeline pages
to replace preview placeholders with actual content previews.
"""

import json
import os
import re
import sqlite3
from pathlib import Path

# Paths
TIMELINE_DB = "/Users/am/Research/Epstein/epstein-wiki/database/timeline.db"
PREVIEW_FILES = [
    "/Users/am/Research/Epstein/epstein-wiki/output/content_previews_batch1.json",
    "/Users/am/Research/Epstein/epstein-wiki/output/content_previews_batch2.json",
    "/Users/am/Research/Epstein/epstein-wiki/output/content_previews_batch3.json",
    "/Users/am/Research/Epstein/epstein-wiki/output/content_previews_batch4.json"
]
YEAR_PAGES_DIR = "/Users/am/Research/Epstein/epstein-wiki/docs/timeline/by_year"


def load_all_previews():
    """Load and merge all content preview batch files."""
    print("Loading content previews...")
    all_previews = {}

    for preview_file in PREVIEW_FILES:
        if not os.path.exists(preview_file):
            print(f"  ⚠ Warning: {os.path.basename(preview_file)} not found")
            continue

        with open(preview_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            previews = data.get('previews', {})
            all_previews.update(previews)
            print(f"  ✓ Loaded {len(previews):,} previews from {os.path.basename(preview_file)}")

    print(f"\nTotal previews loaded: {len(all_previews):,}")
    return all_previews


def get_bates_to_group_mapping(db_path):
    """Create mapping from canonical Bates ID to group ID."""
    print("\nBuilding Bates ID to group ID mapping...")
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute("""
        SELECT canonical_bates, group_id
        FROM timeline_groups
    """)

    mapping = {}
    for bates, group_id in cursor.fetchall():
        mapping[bates] = group_id

    conn.close()
    print(f"  ✓ Mapped {len(mapping):,} canonical documents to group IDs")
    return mapping


def integrate_preview_into_page(file_path, previews, bates_to_group):
    """Update a single year page with content previews."""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    original_content = content
    replacements_made = 0

    # Pattern to find canonical document references
    # Looking for: **Canonical Document:** [HOUSE_OVERSIGHT_XXXXXX](../../documents/HOUSE_OVERSIGHT_XXXXXX.md)
    pattern = r'\*\*Canonical Document:\*\* \[([^\]]+)\]'

    # Find all canonical documents in the page
    matches = list(re.finditer(pattern, content))

    for match in matches:
        bates_id = match.group(1)

        # Get group ID for this Bates ID
        group_id = bates_to_group.get(bates_id)
        if not group_id:
            continue

        # Get preview for this group
        preview_data = previews.get(group_id)
        if not preview_data:
            continue

        # Find the preview section after this canonical document
        # Look for either:
        #   !!! abstract "Content Preview"
        #       *Content preview will be generated by processing agents*
        # OR
        #   !!! abstract "Content Preview"
        #       No preview available

        # Find the position after this match
        search_start = match.end()
        search_text = content[search_start:search_start + 500]  # Look ahead up to 500 chars

        # Try to find placeholder or "No preview available"
        placeholder_pattern = r'!!! abstract "Content Preview"\s+(?:\*Content preview will be generated by processing agents\*|No preview available)'
        placeholder_match = re.search(placeholder_pattern, search_text)

        if placeholder_match:
            # Calculate actual position in full content
            placeholder_start = search_start + placeholder_match.start()
            placeholder_end = search_start + placeholder_match.end()

            # Get the preview text
            # Some entries have 'preview', others have 'summary' (for documents without content)
            if 'preview' in preview_data:
                preview_text = preview_data['preview']
            elif 'summary' in preview_data:
                preview_text = preview_data['summary']
            else:
                preview_text = 'No preview available'

            # Create the replacement text
            replacement = f'!!! abstract "Content Preview"\n    {preview_text}'

            # Replace in content
            content = content[:placeholder_start] + replacement + content[placeholder_end:]
            replacements_made += 1

    # Only write if changes were made
    if replacements_made > 0:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

    return replacements_made


def main():
    """Main execution function."""
    print("=" * 80)
    print("INTEGRATE CONTENT PREVIEWS INTO TIMELINE BY-YEAR PAGES")
    print("=" * 80)
    print()

    # Load all previews
    previews = load_all_previews()
    if not previews:
        print("\n❌ Error: No previews loaded!")
        return

    # Get Bates to group mapping
    bates_to_group = get_bates_to_group_mapping(TIMELINE_DB)
    if not bates_to_group:
        print("\n❌ Error: Could not load Bates to group mapping!")
        return

    print()
    print("=" * 80)
    print("UPDATING YEAR PAGES")
    print("=" * 80)
    print()

    # Get all year pages
    year_pages = sorted([
        f for f in os.listdir(YEAR_PAGES_DIR)
        if f.endswith('.md') and f != 'index.md'
    ])

    total_replacements = 0
    pages_updated = 0

    for page_file in year_pages:
        page_path = os.path.join(YEAR_PAGES_DIR, page_file)

        print(f"Processing {page_file}...", end=" ")
        replacements = integrate_preview_into_page(page_path, previews, bates_to_group)

        if replacements > 0:
            print(f"✓ ({replacements} previews integrated)")
            total_replacements += replacements
            pages_updated += 1
        else:
            print("⚠ (no changes)")

    print()
    print("=" * 80)
    print("INTEGRATION COMPLETE")
    print("=" * 80)
    print()
    print(f"Pages processed: {len(year_pages)}")
    print(f"Pages updated: {pages_updated}")
    print(f"Total previews integrated: {total_replacements:,}")
    print()

    if total_replacements > 0:
        print("✓ Content previews successfully integrated into year pages!")
    else:
        print("⚠ Warning: No previews were integrated. Check that:")
        print("  - Preview files exist and contain data")
        print("  - Year page format matches expected pattern")
        print("  - Bates IDs in year pages match those in database")

    print()


if __name__ == "__main__":
    main()
